Mentor walkthrough -- relates to issue #19
bradreeder/Node-Intro-Workshop pull request #20
Opened 2018-11-09 15:14 UTC by MissArray

Replaced `err` with `error` in various steps.
Relates to #19

2018-11-13 13:30 UTC, mattlub requested changes
can we delete the package.json and package lock in the root?

2018-11-13 14:17 UTC, arrested-developer commented
No PR needed as this is the mentor branch

2018-11-13 14:27 UTC, mattlub commented
@arrested-developer I think we usually prefer having the mentor notes on master but in a folder, for ease of keeping up to date with master. (I think @eliascodes explained this better somewhere in a comment)

2018-11-13 14:40 UTC, eliascodes commented
https://github.com/foundersandcoders/master-reference/issues/456#issuecomment-315138262

2018-11-13 15:01 UTC, arrested-developer commented
Thanks @eliascodes - I think the PR was opened in order to add Art's changes, but they were changes committed directly to the branch...

Reopening the PR so we can move mentor notes to the main branch (#12)

Some attention is needed first:

- [ ] this branch is 2 commits behind master, these changes need merging in
- [ ] mentor notes need to be in a 'solution' or 'mentor notes' folder
- [ ] 'empty' solution, i.e. current contents of master should be in the root folder

2018-11-14 06:49 UTC, mattlub commented
@arrested-developer @eliascodes what about all the `steps` folders?

Should they:
- stay directly in root
- or be nested in, e.g. a `steps` folder
- or in the `mentor notes` folder?

@MissArray do you have time to finish off this PR or should I try to pick it up?

2018-11-14 09:31 UTC, MissArray commented
@mattlub. Entirely up to you and what @arrested-developer thinks is best.
 I have already asked Michael whether he'd like one of the week-4 mentors and me to go through this repo and try to clean it up. I won't have time this week, as I'm working, but should have enough time next week in between mentoring.

2018-11-14 11:31 UTC, arrested-developer commented
@mattlub I think the steps folders are the steps of the code-along for the mentors to follow - so should be moved inside a `solution` folder

2018-11-14 11:48 UTC, mattlub commented
@arrested-developer ok sure@MissArray

2018-11-15 09:05 UTC, mattlub approved these changes

2018-11-15 14:34 UTC, shiryz reviewed
The whole workshop is written in es6 while es6 is being taught the day after...
Would be happy if a note was added about this so no one would have to change the entire ws

2018-11-15 14:34 UTC, shiryz commented on public/index.js
> +    xhr.onreadystatechange = function() {
The only line with es5, check the general comment

2018-11-15 15:25 UTC, m4v15 commented on public/index.js
> +    xhr.onreadystatechange = function() {
Presumably this stuff is all es5 in this file cos it's the client side JS? Like I know that's probably stupid nowadays, but it still gives a chance to talk about the difference environments this code is all running in?

2018-11-15 15:27 UTC, m4v15 commented
@shiryz I agree there needs to be a note added about es6 es5 but can it be in a seperate PR after this has been merged?

2018-11-15 15:47 UTC, shiryz commented
@m4v15 absolutely!

2018-11-15 15:47 UTC, shiryz approved these changes

2018-11-17 09:16 UTC, m4v15 commented
@arrested-developer as it is so close to delivery I wanted to check with you/the mentors for this week in London whether we should merge this or leave it on a branch for now?

2018-11-17 09:52 UTC, MissArray commented
@m4v15 Maybe merge after Monday? At the moment we know where everything is and that it works as expected.

2018-11-17 14:13 UTC, m4v15 commented
@MissArray yep, no problem - are you delivering this week in London?

2018-11-17 17:17 UTC, MissArray commented
@m4v15, yes, Sangita, Dennis and I will be there this week.

2018-11-27 11:29 UTC, mattlub commented
can this be merged now? @m4v15 @MissArray @eliascodes @arrested-developer

2018-11-27 11:42 UTC, MissArray commented
@mattlub So far as I'm concerned, yes, but best to see whether the rest agree.

2018-11-27 13:03 UTC, m4v15 approved these changes

2018-11-27 13:03 UTC, m4v15 commented
leaving for @eliascodes to merge

2018-11-27 13:13 UTC, merged